name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up MinGW
    - uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - run: |
          $flags = '-std=c++14','-o','foo','foo.cpp'
          & '${{ steps.setup.outputs.gxx }}' $flags
